baseURL = "https://www.chris-saylor.com/chessbot"
languageCode = "en-us"
title = "ChessBot"
theme = "github-project-landing-page"
publishDir = "../"

[params]
    description = "Play Chess with your colleagues within Slack."
    project_url = "http://github.com/cjsaylor/chessbot"
    github_project_name = "chessbot"
    github_user_name = "cjsaylor"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"